# The URL the site will be built for
base_url = "https://bluejekyll.github.io/blog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

title = "let blueJEKYLL=benjaminFRY;"
description = "A Self-proclaimed Rust evangelist, Java distributed systems engineer, recovering C/C++ masochist; Pie and bread maker; Cyclist; Raiser of Humans."
email = "benjaminfry@me.com"
twitter = "https://twitter.com/benj_fry"
github = "https://github.com/bluejekyll"
linkedin = "https://www.linkedin.com/in/benjamin-fry-8b83072/"